haxe build.hxml -debug || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
obj\Main-debug.exe || exit /b
